"""Minimal, safe JSON pattern-import format (Category 4 target 4.6,
`COMMERCIAL_RCWA_ATOMIC_TARGETS.md`).

This is a *sougata_solver*-native format, not a CAD/GDS format -- GDS/layout
import remains out of scope (`decisions.md` ADR-005, unchanged by ADR-013's
narrower `Polygon`-primitive revisit). It exists to let a `Pattern` be
described as data (e.g. generated by another script, or hand-written) and
loaded without editing Python source, while staying inside this project's
existing shape/material vocabulary (`Circle`, `Rectangle`, `Ellipse`,
`Polygon`, `Slab`; isotropic scalar-permittivity materials only -- tensor/
dispersive materials are out of scope for this target, matching Phase 2's
own scalar-isotropic-only restriction for Fourier factorization).

**Security** (`rules.md`'s Security Rules and `architecture.md`'s Security
Considerations): uses the standard-library `json` module only -- never
`eval`/`exec`/`pickle` on file content. Every required field is checked
explicitly and raises a clear `ValueError` naming the offending key/shape
index on malformed input, rather than a raw `KeyError`/`TypeError` or a
silent default substitution.

**Scope note**: this target is parser-and-validation only, deliberately
**not wired into `Simulation`/`Layer` construction** yet ("add parser tests
before solver integration," per the atomic-targets register's own wording
for this target) -- `pattern_from_dict`/`pattern_from_json_file` return a
plain `geometry.Pattern`, which a caller can already pass to `Layer(...,
pattern=...)` today using the existing public API; no new solver-side
plumbing was added or is needed for that to work, only formalized as the
next step by a future target if wiring convenience (e.g. a `Layer.from_json`
helper) is ever explicitly requested.

Schema (top level)::

    {
      "unit": "m" | "um" | "nm",        # optional, default "m"
      "background": {"eps_re": <num>, "eps_im": <num, optional, default 0>},
      "shapes": [
        {"type": "circle", "center": [x, y], "radius": r, "material": {...}},
        {"type": "rectangle", "center": [x, y], "halfwidth": [hx, hy],
         "angle_deg": <num, optional, default 0>, "material": {...}},
        {"type": "ellipse", "center": [x, y], "halfwidth": [hx, hy],
         "angle_deg": <num, optional, default 0>, "material": {...}},
        {"type": "polygon", "center": [x, y], "vertices": [[x0,y0], ...],
         "angle_deg": <num, optional, default 0>, "material": {...}},
        {"type": "slab", "center_x": x, "halfwidth": h, "material": {...}}
      ]
    }

All lengths (`center`, `radius`, `halfwidth`, `vertices`, `center_x`) are in
`unit`, converted to meters (this project's internal convention, see
`CONVENTIONS.md`) before constructing any `Shape`.
"""

from __future__ import annotations

import json
import math
from typing import Any

from sougata_solver.geometry import Circle, Ellipse, Pattern, Polygon, Rectangle, Shape, Slab
from sougata_solver.materials import Material

_UNIT_SCALE_M = {"m": 1.0, "um": 1e-6, "nm": 1e-9}

_SHAPE_TYPES = ("circle", "rectangle", "ellipse", "polygon", "slab")


def _require_keys(d: Any, keys: tuple[str, ...], context: str) -> None:
    if not isinstance(d, dict):
        raise ValueError(f"{context}: expected a JSON object, got {type(d).__name__}")
    missing = [k for k in keys if k not in d]
    if missing:
        raise ValueError(f"{context}: missing required key(s) {missing}")


def _require_number(value: Any, context: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{context}: expected a number, got {value!r}")
    return float(value)


def _scaled_number(value: Any, scale: float, context: str) -> float:
    return _require_number(value, context) * scale


def _scaled_point(value: Any, scale: float, context: str) -> tuple[float, float]:
    if not isinstance(value, (list, tuple)) or len(value) != 2:
        raise ValueError(f"{context}: expected a 2-element [x, y] array, got {value!r}")
    return (_scaled_number(value[0], scale, f"{context}[0]"), _scaled_number(value[1], scale, f"{context}[1]"))


def _material_from_dict(d: Any, context: str) -> Material:
    """Isotropic scalar permittivity only -- see module docstring's scope
    note. Optional `"source"` key (Category 5 target 5.8) is passed through
    to `Material.source` unchanged -- purely informational, not validated
    beyond "must be a string" if present."""
    _require_keys(d, ("eps_re",), context)
    eps_re = _require_number(d["eps_re"], f"{context}.eps_re")
    eps_im = _require_number(d.get("eps_im", 0.0), f"{context}.eps_im")
    source = d.get("source")
    if source is not None and not isinstance(source, str):
        raise ValueError(f"{context}.source: expected a string, got {source!r}")
    return Material(context, complex(eps_re, eps_im), source=source)


def _shape_from_dict(d: Any, scale: float, index: int) -> Shape:
    context = f"shapes[{index}]"
    _require_keys(d, ("type", "material"), context)
    shape_type = d["type"]
    if shape_type not in _SHAPE_TYPES:
        raise ValueError(f"{context}: unknown shape type {shape_type!r}; supported types are {_SHAPE_TYPES}")
    material = _material_from_dict(d["material"], f"{context}.material")
    angle = math.radians(_require_number(d.get("angle_deg", 0.0), f"{context}.angle_deg"))

    if shape_type == "circle":
        _require_keys(d, ("center", "radius"), context)
        return Circle(
            center=_scaled_point(d["center"], scale, f"{context}.center"),
            radius=_scaled_number(d["radius"], scale, f"{context}.radius"),
            material=material,
        )
    if shape_type == "rectangle":
        _require_keys(d, ("center", "halfwidth"), context)
        return Rectangle(
            center=_scaled_point(d["center"], scale, f"{context}.center"),
            halfwidth=_scaled_point(d["halfwidth"], scale, f"{context}.halfwidth"),
            material=material,
            angle=angle,
        )
    if shape_type == "ellipse":
        _require_keys(d, ("center", "halfwidth"), context)
        return Ellipse(
            center=_scaled_point(d["center"], scale, f"{context}.center"),
            halfwidth=_scaled_point(d["halfwidth"], scale, f"{context}.halfwidth"),
            material=material,
            angle=angle,
        )
    if shape_type == "polygon":
        _require_keys(d, ("center", "vertices"), context)
        vertices_raw = d["vertices"]
        if not isinstance(vertices_raw, (list, tuple)):
            raise ValueError(f"{context}.vertices: expected a list of [x, y] pairs, got {vertices_raw!r}")
        vertices = tuple(
            _scaled_point(v, scale, f"{context}.vertices[{i}]") for i, v in enumerate(vertices_raw)
        )
        return Polygon(
            center=_scaled_point(d["center"], scale, f"{context}.center"),
            vertices=vertices,
            material=material,
            angle=angle,
        )
    # shape_type == "slab"
    _require_keys(d, ("center_x", "halfwidth"), context)
    return Slab(
        center_x=_scaled_number(d["center_x"], scale, f"{context}.center_x"),
        halfwidth=_scaled_number(d["halfwidth"], scale, f"{context}.halfwidth"),
        material=material,
    )


def pattern_from_dict(data: Any) -> Pattern:
    """Build a `Pattern` from an already-parsed dict matching this module's
    schema (see module docstring). Raises `ValueError` naming the offending
    key/shape index on any malformed input -- never substitutes a silent
    default for a missing required field."""
    _require_keys(data, ("background",), "pattern")
    unit = data.get("unit", "m")
    if unit not in _UNIT_SCALE_M:
        raise ValueError(f"pattern.unit: expected one of {tuple(_UNIT_SCALE_M)}, got {unit!r}")
    scale = _UNIT_SCALE_M[unit]

    background = _material_from_dict(data["background"], "pattern.background")
    pattern = Pattern(background=background)

    shapes_raw = data.get("shapes", [])
    if not isinstance(shapes_raw, (list, tuple)):
        raise ValueError(f"pattern.shapes: expected a list, got {shapes_raw!r}")
    for i, shape_dict in enumerate(shapes_raw):
        pattern.add(_shape_from_dict(shape_dict, scale, i))
    return pattern


def pattern_from_json_string(text: str) -> Pattern:
    """Parse a JSON string and build a `Pattern` from it (`json.loads`
    only -- never `eval`/`exec`)."""
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"pattern JSON: invalid JSON ({exc})") from exc
    return pattern_from_dict(data)


def pattern_from_json_file(path: str) -> Pattern:
    """Read `path` and build a `Pattern` from its JSON content (`json.load`
    only -- never `eval`/`exec`)."""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    return pattern_from_json_string(text)
